server:
  port: 8094
  servlet:
    context-path: /
spring:
  datasource:
        #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
#dubbo配置信息    
dubbo:
  scan:
    basePackages: com.jt  #dubbo包扫描
  application:
    name: provider-cart   #定义服务名称
  registry:
    address: zookeeper://192.168.161.129:2181?backup=192.168.161.129:2182,192.168.161.129:2183
  protocol:
    name: dubbo
    port: 20881 #dubbo rbc通信端口
    
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.jt.mapper: debug
